### ISSUE TITLE
ArchLinux compilation error after OpenCV 4: ‘initUndistortRectifyMap’ is not a member of ‘cv’

### ISSUE THREAD

**Issue by elmuz** [CMU-Perceptual-Computing-Lab/openpose#956]
### Issue Summary
After upgrading OpenCV from 3.4 to 4.0 I am not able to build Openpose anymore. I get a compilation error with the message: `‘initUndistortRectifyMap’ is not a member of ‘cv’`.

### Executed Command (if any)
I cloned the latest repository source code and I went on with the usual cmake approach. I created a 'build' folder and from there I ran:
```
cmake \                                                                                                                                         alessio@marta
    -DCMAKE_BUILD_TYPE:STRING="Release" \
    -DBUILD_CAFFE:BOOL=OFF \
    -DBUILD_EXAMPLES:BOOL=OFF \
    -DBUILD_DOCS:BOOL=ON \
    -DBUILD_SHARED_LIBS:BOOL=ON \
    -DDOWNLOAD_BODY_25_MODEL:BOOL=ON \
    -DDOWNLOAD_BODY_COCO_MODEL:BOOL=OFF \
    -DDOWNLOAD_BODY_MPI_MODEL:BOOL=OFF \
    -DDOWNLOAD_FACE_MODEL:BOOL=OFF \
    -DDOWNLOAD_HAND_MODEL:BOOL=OFF \
    -DWITH_3D_RENDERER:BOOL=OFF \
    -DCMAKE_CXX_FLAGS:STRING="-I/opt/intel/compilers_and_libraries_2018.3.222/linux/mkl/include" \
    -DCMAKE_C_FLAGS:STRING="-I/opt/intel/compilers_and_libraries_2018.3.222/linux/mkl/include" \
    -DCaffe_INCLUDE_DIRS:PATH="/usr/include/caffe" \
    -DCaffe_LIBS:PATH="/usr/lib/libcaffe.so" \
    -DCMAKE_INSTALL_PREFIX:PATH="/usr/local" \
    -DCMAKE_CXX_COMPILER=/usr/bin/g++-7 \
    -DCMAKE_C_COMPILER=/usr/bin/gcc-7 -DWITH_OPENCV_WITH_OPENGL=ON -DBUILD_PYTHON=ON -DINSTRUCTION_SET=AVX ../
```
### OpenPose Output (if any)
```
[...] # docstring compilation messages...
[  1%] Built target doc_doxygen
[  2%] Building NVCC (Device) object src/openpose/CMakeFiles/openpose.dir/tracking/openpose_generated_pyramidalLK.cu.o
[  2%] Building NVCC (Device) object src/openpose/CMakeFiles/openpose.dir/face/openpose_generated_renderFace.cu.o
[  2%] Building NVCC (Device) object src/openpose/CMakeFiles/openpose.dir/hand/openpose_generated_renderHand.cu.o
[  3%] Building NVCC (Device) object src/openpose/CMakeFiles/openpose.dir/net/openpose_generated_bodyPartConnectorBase.cu.o
[  3%] Building NVCC (Device) object src/openpose/CMakeFiles/openpose.dir/net/openpose_generated_maximumBase.cu.o
[  4%] Building NVCC (Device) object src/openpose/CMakeFiles/openpose.dir/net/openpose_generated_nmsBase.cu.o
[  4%] Building NVCC (Device) object src/openpose/CMakeFiles/openpose.dir/net/openpose_generated_resizeAndMergeBase.cu.o
[  4%] Building NVCC (Device) object src/openpose/CMakeFiles/openpose.dir/pose/openpose_generated_renderPose.cu.o
Scanning dependencies of target openpose
[  4%] Building CXX object src/openpose/CMakeFiles/openpose.dir/3d/cameraParameterReader.cpp.o
/home/alessio/build/openpose/src/openpose/3d/cameraParameterReader.cpp: In member function ‘void op::CameraParameterReader::undistort(cv::Mat&, unsigned int)’:
/home/alessio/build/openpose/src/openpose/3d/cameraParameterReader.cpp:302:25: error: ‘initUndistortRectifyMap’ is not a member of ‘cv’
                     cv::initUndistortRectifyMap(
                         ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
make[2]: *** [src/openpose/CMakeFiles/openpose.dir/build.make:119: src/openpose/CMakeFiles/openpose.dir/3d/cameraParameterReader.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:222: src/openpose/CMakeFiles/openpose.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

```

### Errors (if any)
```
/home/alessio/build/openpose/src/openpose/3d/cameraParameterReader.cpp:302:25: error: ‘initUndistortRectifyMap’ is not a member of ‘cv’
                     cv::initUndistortRectifyMap(
                         ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
```

### Type of Issue
- Compilation/installation error

### Your System Configuration
1. std output [pastebin](https://pastebin.com/HizBt7UL)
std error [pastebin](https://pastebin.com/NTNpgf5h)

2. **OpenPose version**: Latest GitHub

3. **General configuration**:
    - **Installation mode**: CMake
    - **Operating system**: ArchLinux
    - **Release or Debug mode**: Release
    - **Compiler**: gcc-7 v7.4.1

4. **Non-default settings**:
    - **3-D Reconstruction module added**: no

5. **3rd-party software**:
    - **Caffe version**: 1.0 (AUR pkg 'caffe-cuda', based on https://github.com/BVLC/caffe/archive/1.0.tar.gz)
    - **CMake version**: 3.13.1
    - **OpenCV version**: 4.0

**Comment by philipNoonan** [comment]
The initUndistortRectifyMap has been moved in opencv4, and its gone into a header that is currently not included in openpose. If you add 

#include <opencv2/calib3d.hpp> 

to openpose/src/openpose/3d/cameraParameterReader.cpp, then the error should go away.

**Comment by gineshidalgo99** [comment]
@philipNoonan Thanks! I will push a fix based on your answer (but still compatible with older versions too) soon (1-3 days).

**Comment by philipNoonan** [comment]
@gineshidalgo99  Happy to help :) I'm in the process of building OP for a Jetson Xavier so I'm coming accross a few compatibility issues with caffe/opencv4/openpose/cuda10. I'll do a write up/PR once its all working if that would be useful?

**Comment by elmuz** [comment]
@philipNoonan, @gineshidalgo99 thank you very much to both of you! It's working now.

**Comment by vasanthhr** [comment]
I got the same issue. can someone help me here.

https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1087
