### ISSUE TITLE
Compilation/installation error:  errors on make, custom Caffe and OpenCV

### ISSUE THREAD

**Issue by metalaman** [CMU-Perceptual-Computing-Lab/openpose#412]
**Compilation/installation error**

**Operating System**:
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

**CUDA version** : CUDA Version 8.0.61
**cuDNN version**: Default, which openpose adds.
**Caffe version**: 1.0.0 Built separately 
**OpenCV version**: 3.3.0 Built separatedly
Compiler : gcc (Ubuntu 5.4.1-2ubuntu1~16.04) 5.4.1 20160904

My Caffe and OpenCV got successfully built.
I get the following error during make;

`[ 93%] Linking CXX executable openpose.bin
../../src/openpose/libopenpose.so.1.2.1: undefined reference to `caffe::Net<float>::blob_by_name(std::string const&) const'
../../src/openpose/libopenpose.so.1.2.1: undefined reference to `google::base::CheckOpMessageBuilder::NewString()'
../../src/openpose/libopenpose.so.1.2.1: undefined reference to `op::cudaCheck(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../../src/openpose/libopenpose.so.1.2.1: undefined reference to `op::error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../../src/openpose/libopenpose.so.1.2.1: undefined reference to `caffe::Net<float>::Net(std::string const&, caffe::Phase, int, std::vector<std::string, std::allocator<std::string> > const*)'
../../src/openpose/libopenpose.so.1.2.1: undefined reference to `caffe::Net<float>::CopyTrainedLayersFrom(std::string)'
collect2: error: ld returned 1 exit status
examples/tutorial_pose/CMakeFiles/2_extract_pose_or_heatmat_from_image.bin.dir/build.make:149: recipe for target 'examples/tutorial_pose/2_extract_pose_or_heatmat_from_image.bin' failed
make[2]: *** [examples/tutorial_pose/2_extract_pose_or_heatmat_from_image.bin] Error 1
CMakeFiles/Makefile2:1153: recipe for target 'examples/tutorial_pose/CMakeFiles/2_extract_pose_or_heatmat_from_image.bin.dir/all' failed
make[1]: *** [examples/tutorial_pose/CMakeFiles/2_extract_pose_or_heatmat_from_image.bin.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
../../src/openpose/libopenpose.so.1.2.1: undefined reference to `caffe::Net<float>::blob_by_name(std::string const&) const'
../../src/openpose/libopenpose.so.1.2.1: undefined reference to `google::base::CheckOpMessageBuilder::NewString()'
../../src/openpose/libopenpose.so.1.2.1: undefined reference to `op::cudaCheck(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../../src/openpose/libopenpose.so.1.2.1: undefined reference to `op::error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../../src/openpose/libopenpose.so.1.2.1: undefined reference to `caffe::Net<float>::Net(std::string const&, caffe::Phase, int, std::vector<std::string, std::allocator<std::string> > const*)'
../../src/openpose/libopenpose.so.1.2.1: undefined reference to `caffe::Net<float>::CopyTrainedLayersFrom(std::string)'
collect2: error: ld returned 1 exit status
examples/tutorial_pose/CMakeFiles/1_extract_from_image.bin.dir/build.make:149: recipe for target 'examples/tutorial_pose/1_extract_from_image.bin' failed
make[2]: *** [examples/tutorial_pose/1_extract_from_image.bin] Error 1
CMakeFiles/Makefile2:1190: recipe for target 'examples/tutorial_pose/CMakeFiles/1_extract_from_image.bin.dir/all' failed
make[1]: *** [examples/tutorial_pose/CMakeFiles/1_extract_from_image.bin.dir/all] Error 2
../../src/openpose/libopenpose.so.1.2.1: undefined reference to `caffe::Net<float>::blob_by_name(std::string const&) const'
../../src/openpose/libopenpose.so.1.2.1: undefined reference to `google::base::CheckOpMessageBuilder::NewString()'
../../src/openpose/libopenpose.so.1.2.1: undefined reference to `op::cudaCheck(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../../src/openpose/libopenpose.so.1.2.1: undefined reference to `op::error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../../src/openpose/libopenpose.so.1.2.1: undefined reference to `caffe::Net<float>::Net(std::string const&, caffe::Phase, int, std::vector<std::string, std::allocator<std::string> > const*)'
../../src/openpose/libopenpose.so.1.2.1: undefined reference to `caffe::Net<float>::CopyTrainedLayersFrom(std::string)'
collect2: error: ld returned 1 exit status
examples/openpose/CMakeFiles/openpose.bin.dir/build.make:149: recipe for target 'examples/openpose/openpose.bin' failed
make[2]: *** [examples/openpose/openpose.bin] Error 1
CMakeFiles/Makefile2:1041: recipe for target 'examples/openpose/CMakeFiles/openpose.bin.dir/all' failed
make[1]: *** [examples/openpose/CMakeFiles/openpose.bin.dir/all] Error 2
`
I've tried building Caffe using openpose but I get protobuf unresolved dependencies during make.
While building caffe separately I solved protobuf unresolved dependencies by compiling Caffe with g++-5, don't know how to do this with openpose building everything.

Any help is appreciated.
Thanks.

**Comment by gineshidalgo99** [comment]
OpenPose does not directly use protobuf, but rather OpenCV and Caffe use it. So there is some flag in OpenCV build that includes it, and it's affecting Caffe. Only one of them can use it (and Caffe needs it for sure), so it must be disabled from OpenCV. I  am not sure the exact flag in OpenCV build that causes this. I'd highly appreciate if you could let us know if you figure it out. Thanks!

**Comment by metalaman** [comment]
I fixed the original issue by building using g++-5.  Saw `std::unique_ptr<>` in netCaffe.hpp which is available in c++11 onwards so had to compile with newer g++.
The option that you are looking for is BUILD_PROTOBUF. By default it is ON.

**Comment by gineshidalgo99** [comment]
Thank you for the feed-back!
