### ISSUE TITLE
Unable to install openpose. fatal error: 'cblas.h' file not found #include <cblas.h> . arm64 (m1 mac)

### ISSUE THREAD

**Issue by awadbs** [CMU-Perceptual-Computing-Lab/openpose#2125]
### Issue Summary

I am unable to make openpose. I keep getting an error that cblas.h was not found. The output is below.

I followed all steps upto compilation, [here](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation/0_index.md#compilation), intalled the prereqs and I get stopped at the final step of compilation: 'make -j`sysctl -n hw.logicalcpu` .
Saying cblas.h is not found. I am using python 3.9.10 with pyenv. 
I also tried building caffe seperately as instructed [here](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation/0_index.md#mac) but no luck. Still get the cblas.h error again. 
I have an arm64 cpu (Apple M1 Pro), running on macOS Monterey 12.2.1.

I feel like i've exhausted all my options, is there anything else I should try?

### Executed Command (if any)

   - install prereqs, and clone openpose [instructions](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation/0_index.md#compilation)

```
cd build/
make -j`sysctl -n hw.logicalcpu`
```

### Errors (if any)
```
.../openpose/build/caffe/include/caffe/util/mkl_alternate.hpp:14:10: fatal error: 'cblas.h' file not found
#include <cblas.h>
         ^~~~~~~~~
         ```

### Type of Issue
Select the topic(s) on your post, delete the rest:
- Compilation/installation error

### Your System Configuration

3. Console output [PasteBin](https://pastebin.com/WJxuuQav)

4. **OpenPose version**: Latest GitHub code

5. **General configuration**:
    - Installation mode: CMake
    - macOS Monterey
    - OS Version: 12.2.1
    - compiler cmake

6. **Non-default settings**:
     - GPU_MODE=CPU_ONLY and BUILD_PYTHON=TRUE and PYTHON_EXECUTABLE=/Users/name/.pyenv/shims/python) 
 (my python exec path since I installed python via pyenv, and not homebrew, as suggested [here](https://github.com/pybind/pybind11/issues/2154) )

7. **3rd-party software**:
    - **Caffe version**: Default from OpenPose
    - **CMake version** : cmake version 3.24.0
    - **OpenCV version**:  (4.6.0)[https://docs.opencv.org/4.x/d0/db2/tutorial_macos_install.html]

10. If **Python** API:
    - **Python version**: 2.7, 3.7, ...? 3.9.10 (pyenv install)
    - **Numpy version** : 1.23.2

**Comment by awadbs** [comment]
> Getting the same error!! Stuck on it since a long time, any resolutions?

What OS, CPU, and GPU do you use, and is your python installed via pyenv?

**Comment by yuchenrao** [comment]
You can check issue #1942

**Comment by franzcrs** [comment]
Solved by modifying the CMakeLists.txt file as introduced in #1942
In case you face more errors you can refer to the changes I did for building **OpenPose with Caffe** uploaded to [this repository](https://github.com/franzcrs/openpose-with-caffe-for-MacM1). All changes are grouped in the [commit e0e5833](https://github.com/franzcrs/openpose-with-caffe-for-MacM1/commit/e0e5833108d557d57ab825179f21f57444810c7e). The steps I followed for a successful installation in my Mac M1 are displayed in the Readme. I hope M1 Mac users can find this helpful.
