### ISSUE TITLE
Error in deploying with external application, Windows 10, Visual Studio 2017

### ISSUE THREAD

**Issue by ianni67** [CMU-Perceptual-Computing-Lab/openpose#1446]
### Issue Summary
I'm experiencing a weird compilation error while building an external application ([zed-openflow](https://github.com/adujardin/zed-openpose)) under Windows 10 with Visual Studio 2017. 
```
Error	C2664	'op::Point<int> op::flagsToPoint(const op::String &,const op::String &)': cannot convert argument 1 from 'fLS::clstring' to 'const op::String &'	
zed_openpose	C:\Users\ianni\Desktop\SW\zed-openpose\src\main.cpp	173	
```
As the code in zed-openpose uses the flagsToPoint function in the same way as it is used in openpose demo, i believe this is not an error in using the function. 
Looks like this error is somewhat related to some recent changes in the OpenPose code, made on Oct. 2019 but cannot confirm that. I tried re-installing, re-compiling, explicitely casting, to no avail. The error repeates for each FLAG that is converted with flagsToPoint in the code I'm trying to build.

Everything worked fine in Ubuntu 18.04, with previous version of openpose and the same version of zed-openpose.

Please, help or advice. I'm stuck.

### Type of Issue
- Compilation/Deployment error

### Your System Configuration

2. **OpenPose version**: Latest GitHub code (commit 254570d)

3. **General configuration**:
    - **Installation mode**: CMake, Windows 10, Visual Studio 2017
    - **Operating system**: Windows 10
    - **Release or Debug mode**: BOTH
    - **Compiler VS2017 community (Windows 10)**

4. **Non-default settings**:
    - **3-D Reconstruction module added**? **NO**
    - Any other custom CMake configuration with respect to the default version?: **NO**

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose
    - **CMake version**: 3.16-rc1
    - **OpenCV version**: OpenPose default (Windows) 

6. If **GPU mode** issue:
    - **CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): 10.2
    - **cuDNN version**:
    - **GPU model** (`nvidia-smi` in Ubuntu): GEForce GTX 1070

9. If **Windows** system:
    - Portable demo or compiled library? **Compiled Library**

**Comment by ianni67** [comment]
... looks like this issue is being fixed at the external application side. (https://github.com/adujardin/zed-openpose/issues/9). 
Thank you anyway.
