### ISSUE TITLE
Can OpenPose be used on Nvidia Jetson TK1 with cuda 6.5 

### ISSUE THREAD

**Issue by cortinas** [CMU-Perceptual-Computing-Lab/openpose#44]
### Issue summary
Can OpenPose be used on Jetson TK1 with cuda 6.5 

### Type of issue
- Question

### Your system configuration
**Operating system** ubunutu 14.04
**CUDA version** 6.5
**cuDNN version**:
**GPU model** Nvidia jetson tk1
**Caffe version**: Default from OpenPose or custom version.
**OpenCV version**: Opencv 2.4

**Comment by gineshidalgo99** [comment]
You should be able by reducing the `--net_resolution` to if fits on GPU memory and using your custom Caffe version (the one that actually compiles on CUDA 6.5 on the Jetson TK1).

Other than that it should be easy to install. If you could share (pull request?) the instructions, it will definitively help other people.

Thanks!

**Comment by cortinas** [comment]
thanks. No problem. I will attempt to build first and then come back 
The caffe/cuda/cudnn environment on the Jetson tk1 is a bit of a mess as tk1 only supports cuda6.5 
I can build the latest caffe but only with cudnn switched off.
More news as I test

**Comment by cortinas** [comment]
Ok I am getting a compilation error running "make all". Caffe built fine and the webapp demo runs ok

Here are the last few lines of the compilation

`CXX src/openpose/producer/videoCaptureReader.cpp
CXX src/openpose/producer/webcamReader.cpp
CXX src/openpose/producer/videoReader.cpp
CXX src/openpose/producer/producer.cpp
CXX src/openpose/producer/defineTemplates.cpp
NVCC src/openpose/pose/poseRenderGpu.cu
./include/openpose/pose/poseParameters.hpp(13): error: no instance of constructor "std::map<_Key, _Tp, _Compare, _Alloc>::map [with _Key=unsigned char, _Tp=std::string, _Compare=std::less<unsigned char>, _Alloc=std::allocator<std::pair<const unsigned char, std::string>>]" matches the argument list
            argument types are: ({...}, {...}, {...}, {...}, {...}, {...}, {...}, {...}, {...}, {...}, {...}, {...}, {...}, {...}, {...}, {...}, {...}, {...}, {...})

./include/openpose/pose/poseParameters.hpp(35): error: no instance of constructor "std::vector<_Tp, _Alloc>::vector [with _Tp=unsigned char, _Alloc=std::allocator<unsigned char>]" matches the argument list
            argument types are: (int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int)

./include/openpose/pose/poseParameters.hpp(36): internal error: assertion failed at: "/dvs/p4/build/sw/rel/gpu_drv/r343/r343_00/drivers/compiler/edg/EDG_4.8/src/decl_inits.c", line 3135


2 errors and 1 catastrophic error detected in the compilation of "/tmp/tmpxft_000020d7_00000000-15_poseRenderGpu.compute_52.cpp1.ii".
Compilation aborted.
Aborted
make: *** [.build_release/cuda/src/openpose/pose/poseRenderGpu.o] Error 1

**Comment by gineshidalgo99** [comment]
Sorry for the late response. Were you able to fix it at the end?
The compilation errors are standard C++11 code, is C++11 enabled?
I also guess than https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/58#issuecomment-307590244 might be useful.

**Comment by gineshidalgo99** [comment]
For now I will close it due to no answers. Still, #58 was able to install it on a Jetson.

**Comment by YorksonChang** [comment]
@cortinas  hey，I’m faced with the same issue，have you solved it？thx

**Comment by airobots** [comment]
It works for me. Only need to compile caffe with Jetson's CUDA and change --net_resolution to a smaller resolution to prevent out of memory.

**Comment by megashigger** [comment]
@airobots how many FPS are you able to get on the tk1? and with which net resolution?
