### ISSUE TITLE
[MacOSX] Incomplete compiling documentation.

### ISSUE THREAD

**Issue by djly** [CMU-Perceptual-Computing-Lab/openpose#642]
### Issue Summary

From the documentation about osx: 
> OSX - Caffe, OpenCV, and Caffe prerequisites:
> Install deps by running sudo bash 3rdparty/osx/install_deps.sh on your terminal.
> Current OSX has only been tested with the CPU Version, and hence must be compiled with the -DGPU_MODE=CPU_ONLY flag.

Some notes that I came into when trying to compile on macOS High Sierra (10.13.4). Forgive me if things I'm mentioning are trivial. I tried my best to follow the documentation but there were things I had to troubleshoot to get it to work. I'm hoping to improve the clarity of the documentation.

Using `$build make -j'nproc'` to build. I came across 3 things.

1. It was unclear that I had to build with
```
cd build/
sudo make install
```
to get caffe built for the OSX version. I initially assumed that install_dep.sh was gonna handle that based on the existing wording.

2. `WITH_EIGEN` was not included in the cmake. I had to add `WITH_EIGEN` for the build to continue. As I understand there are instructions that say this is optional step, but by default it breaks the build.
```
src/openpose/calibration/cameraParameterEstimation.cpp:5:14: fatal error: 'Eigen/Dense' file not found
    #include <Eigen/Dense>
             ^~~~~~~~~~~~~
```

3. Similar to #8, I was receiving build errors while building
```
src/openpose/calibration/cameraParameterEstimation.cpp:321:32: error: no member named 'accumulate' in namespace 'std'
                average = std::accumulate(anglesNormalized.begin(), anglesNormalized.end(), 0.)
                          ~~~~~^
1 error generated.
make[2]: *** [src/openpose/CMakeFiles/openpose.dir/calibration/cameraParameterEstimation.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src/openpose/CMakeFiles/openpose.dir/all] Error 2
make: *** [all] Error 2
```
The addition of `#include <numeric>` to the top of `src/openpose/calibration/cameraParameterEstimation.cpp` allowed it to compile.

### Type of Issue
- Compilation/installation error
- Documentation

### Your System Configuration
1. **OpenPose version**: master bcbf349

2. **General configuration**:
   - **Installation mode**: cmake
   - **Release or Debug mode**:  release
   - **Operating system**: 

```
System Version: macOS 10.13.4 (17E202)
Kernel Version: Darwin 17.5.0
```
   - **Compiler**: 
```
$ gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.5.0
Thread model: posix
```

3. **Non-default settings**:
    CPU_ONLY

4. **3rd-party software**:
    - **Caffe version**: Default Build
    - **CMake version**: cmake 3.11.3
    - **OpenCV version**: osx default install_deps.sh

**Comment by djly** [comment]
To add to that, after these 3 things I was able to build and run the binaries.

**Comment by soulslicer** [comment]
Thanks for letting me know. It seemed to work on my Mac.

Can I check how you installed Eigen? With brew?

**Comment by djly** [comment]
I did not install it manually, I didn't think I needed to. It got built when I added the flag.

**Comment by soulslicer** [comment]
Can you paste your cmake command

**Comment by djly** [comment]
<img width="1104" alt="screen shot 2018-06-06 at 3 08 14 pm" src="https://user-images.githubusercontent.com/1790958/41059758-768332ee-699b-11e8-8142-44e6df732145.png">

**Comment by gineshidalgo99** [comment]
@djly Thanks for your feed-back. I have just pushed a fix (with the help of @soulslicer ) to the problems 2 and 3. Please, feel free to try the newest version. It should directly work with no issues. Thanks! (Keep posting if the error persists)
